### ISSUE TITLE
Робота с світлинами #2

### ISSUE THREAD

**Issue by DajanaD** [Dmytro-Ostrenko/API_Wizards#3]
Користувачі можуть завантажувати світлини з описом (POST).
Користувачі можуть видаляти світлини (DELETE).
Користувачі можуть редагувати опис світлини (PUT).
Користувачі можуть отримувати світлину за унікальним посиланням (GET).
Можливість додавати до 5 тегів під світлину. Додавання тегу не обов'язкове при завантаженні світлини.
Теги унікальні для всього застосунку. Тег передається на сервер по імені. Якщо такого тега не існує, то він створюється, якщо існує, то для світлини береться існуючий тег з такою назвою.
Користувачі можуть виконувати базові операції над світлинами, які дозволяє сервіс Cloudinary (https://cloudinary.com/documentation/image_transformations). Можливо вибрати обмежений набір трансформацій над світлинами для свого застосунку з Cloudinary.
Користувачі можуть створювати посилання на трансформоване зображення для перегляду світлини в вигляді URL та QR-code (https://pypi.org/project/qrcode/). Операція POST, оскільки створюється окреме посилання на трансформоване зображення, яке зберігається в базі даних
Створені посилання зберігаються на сервері і через мобільний телефон ми можемо відсканувати QR-code та побачити зображення

**Comment by Warmillie** [comment]
Кристина
